import { weekdayOf } from '@planner/core';
import { expect, test, type Page } from '@playwright/test';
import {
  addSubjectViaUi,
  bogotaToday,
  completeOnboarding,
  expectNoHorizontalOverflow,
  register,
  uniqueEmail,
  watch,
} from './helpers';

// A period that always contains "today" and the weeks around it (the system clock decides what today is).
const period = () => ({ start: bogotaToday(-70), end: bogotaToday(120) });
const nav = (page: Page) => page.getByRole('navigation', { name: 'Principal' });

/**
 * "mañana" as a weekday name. Typing tomorrow's weekday always resolves to tomorrow (never to today or to next
 * week), so the expected date does not depend on the time of day the test runs at.
 */
const TOMORROW = bogotaToday(1);
const DAY_NAMES = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'];
const tomorrowName = DAY_NAMES[weekdayOf(TOMORROW) - 1]!;

async function newUser(page: Page, subjects: string[] = ['Redes']) {
  await register(page, uniqueEmail());
  await completeOnboarding(page, 'Semestre de prueba', period());
  for (const name of subjects) await addSubjectViaUi(page, name);
}

const capture = (page: Page) => page.getByRole('region', { name: 'Captura rápida' });
const textbox = (page: Page) => capture(page).getByLabel('Escribe la actividad en una frase');
const preview = (page: Page) =>
  capture(page).getByRole('group', { name: 'Vista previa de la actividad' });
const create = (page: Page) => preview(page).getByRole('button', { name: 'Crear actividad' });

async function interpret(page: Page, text: string) {
  await page.goto('/dashboard');
  await textbox(page).fill(text);
  await capture(page).getByRole('button', { name: 'Interpretar' }).click();
  await expect(preview(page)).toBeVisible();
}

const activities = async (page: Page) =>
  (await (await page.request.get('/api/activities')).json()).activities as {
    id: string;
    title: string;
    type: string;
    subjectId: string;
    hasTime: boolean;
    dueAt: string;
    status: string;
  }[];
const subjects = async (page: Page) =>
  (await (await page.request.get('/api/subjects')).json()).subjects as {
    id: string;
    name: string;
  }[];

test('capture -> interpret -> confirm: the whole flow, down to reminders, Radar and Attention', async ({
  page,
}) => {
  const assertClean = watch(page);

  // 1-4. New user, current period, subject "Redes", Dashboard.
  await newUser(page);
  await page.goto('/dashboard');
  await expect(
    capture(page).getByRole('heading', { level: 2, name: 'Captura rápida' }),
  ).toBeVisible();
  await expect(textbox(page)).toHaveAttribute('placeholder', 'Ej: parcial redes martes 10am');

  // 5-6. Write the phrase and interpret it: Enter does NOT create anything.
  await textbox(page).fill(`parcial redes ${tomorrowName} 10am`);
  await textbox(page).press('Enter');
  await expect(preview(page)).toBeVisible();
  expect(await activities(page)).toHaveLength(0);

  // 7. The proposal: type, subject, date, time and title. Focus moves to it.
  await expect(preview(page)).toBeFocused();
  await expect(preview(page).getByLabel('Tipo')).toHaveValue('EXAM');
  await expect(preview(page).getByLabel('Asignatura')).toHaveValue((await subjects(page))[0]!.id);
  await expect(preview(page).getByLabel('Fecha')).toHaveValue(TOMORROW);
  await expect(preview(page).getByLabel('Hora (opcional)')).toHaveValue('10:00');
  await expect(preview(page).getByLabel('Título')).toHaveValue('Parcial');
  await expect(preview(page)).toContainText(
    /(Lunes|Martes|Miércoles|Jueves|Viernes|Sábado|Domingo) \d{1,2} de [a-záéíóú]+/,
  );
  await expect(preview(page)).toContainText('no se guarda nada hasta que pulses');
  await expectNoHorizontalOverflow(page);

  // 8-10. Edit the title and confirm: only now is it created.
  await preview(page).getByLabel('Título').fill('Parcial 1');
  await create(page).click();
  await expect(
    capture(page).getByRole('status').filter({ hasText: 'Actividad creada: Parcial 1.' }),
  ).toBeVisible();
  await expect(preview(page)).toHaveCount(0);
  await expect(textbox(page)).toHaveValue('');

  // 11-12. The activity exists, with the edited title, as an ordinary pending activity.
  const [created] = await activities(page);
  expect(created).toMatchObject({
    title: 'Parcial 1',
    type: 'EXAM',
    status: 'PENDING',
    hasTime: true,
  });
  await nav(page).getByRole('link', { name: 'Actividades' }).click();
  await expect(page.getByRole('listitem').filter({ hasText: 'Parcial 1' })).toBeVisible();

  // 13. Its automatic reminders were generated by the normal creation (3 h before tomorrow 10:00 is always ahead).
  await page.getByRole('button', { name: 'Editar Parcial 1', exact: true }).click();
  const edit = page.getByRole('dialog', { name: 'Editar actividad' });
  await expect(
    edit
      .getByRole('region', { name: 'Recordatorios' })
      .getByRole('listitem')
      .filter({ hasText: 'Automático, 3 horas antes' }),
  ).toBeVisible();
  await edit.getByRole('button', { name: 'Cancelar' }).first().click();

  // 14-15. Back on the Dashboard it takes part in "¿Qué hago ahora?" and in the Radar, with no reload.
  await nav(page).getByRole('link', { name: 'Inicio' }).click();
  await expect(
    page
      .getByRole('region', { name: '¿Qué hago ahora?' })
      .getByRole('article', { name: 'Parcial 1' }),
  ).toBeVisible();
  await expect(page.getByRole('region', { name: 'Radar académico' })).toBeVisible();
  await page.goto('/radar');
  await expect(page.getByRole('listitem').filter({ hasText: 'Parcial 1' })).toBeVisible();

  // 16. No console errors, no uncaught exceptions and no failed API calls along the whole flow.
  assertClean();
});

test('without a time the activity has no time (hasTime false)', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page);
  await interpret(page, `tarea redes ${tomorrowName}`);
  await expect(preview(page).getByLabel('Tipo')).toHaveValue('TASK');
  await expect(preview(page).getByLabel('Fecha')).toHaveValue(TOMORROW);
  await expect(preview(page).getByLabel('Hora (opcional)')).toHaveValue('');
  await create(page).click();
  await expect(capture(page).getByRole('status')).toContainText('Actividad creada: Tarea.');
  const [created] = await activities(page);
  expect(created).toMatchObject({ title: 'Tarea', hasTime: false, type: 'TASK' });
  // No time: due at the end of the local day (23:59:59.999 in Bogotá is 04:59:59.999 UTC of the next day).
  expect(created!.dueAt.endsWith('T04:59:59.999Z')).toBe(true);
  assertClean();
});

test('an ambiguous subject asks which one: nothing is chosen for the student', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page, ['Programación I', 'Programación II']);
  await interpret(page, `parcial programacion ${tomorrowName}`);

  await expect(preview(page).getByText('Encontré más de una asignatura posible.')).toBeVisible();
  const choice = preview(page).getByRole('group', { name: '¿A cuál te refieres?' });
  await expect(choice.getByRole('radio')).toHaveCount(2);
  await expect(choice.getByRole('radio', { checked: true })).toHaveCount(0);
  await expect(preview(page).getByLabel('Asignatura')).toHaveValue('');
  await expect(create(page)).toBeDisabled();
  await expect(preview(page)).toContainText('Para crearla falta la asignatura.');

  // Operable with the keyboard.
  await choice.getByRole('radio', { name: 'Programación II' }).focus();
  await page.keyboard.press('Space');
  await expect(choice.getByRole('radio', { name: 'Programación II' })).toBeChecked();
  await expect(create(page)).toBeEnabled();
  await create(page).click();
  await expect(capture(page).getByRole('status')).toContainText('Actividad creada: Parcial.');
  const chosen = (await subjects(page)).find((s) => s.name === 'Programación II')!;
  expect((await activities(page))[0]!.subjectId).toBe(chosen.id);
  assertClean();
});

test('a partial understanding is a preview, not an error: the student completes it', async ({
  page,
}) => {
  const assertClean = watch(page);
  await newUser(page);
  await interpret(page, 'parcial mañana');
  await expect(preview(page).getByLabel('Tipo')).toHaveValue('EXAM');
  await expect(preview(page).getByLabel('Fecha')).toHaveValue(TOMORROW);
  await expect(preview(page).getByLabel('Asignatura')).toHaveValue('');
  await expect(preview(page).getByText('No reconocí una asignatura.')).toBeVisible();
  await expect(create(page)).toBeDisabled();

  await preview(page).getByLabel('Asignatura').selectOption({ label: 'Redes' });
  await expect(create(page)).toBeEnabled();
  await create(page).click();
  await expect(capture(page).getByRole('status')).toContainText('Actividad creada: Parcial.');
  expect((await activities(page))[0]).toMatchObject({ title: 'Parcial', type: 'EXAM' });
  assertClean();
});

test('unknown text gives an incomplete preview and unknown dates are asked for', async ({
  page,
}) => {
  const assertClean = watch(page);
  await newUser(page);
  await interpret(page, 'asdf xyz');
  await expect(preview(page).getByLabel('Título')).toHaveValue('Asdf xyz');
  await expect(preview(page).getByText('No encontré una fecha.')).toBeVisible();
  await expect(create(page)).toBeDisabled();
  await expect(preview(page)).toContainText('Para crearla falta la asignatura, la fecha.');
  assertClean();
});

test('several activities in one phrase: a clear warning, still one proposal', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page, ['Redes', 'Bases de Datos']);
  await interpret(page, 'parcial redes martes y tarea bases viernes');
  await expect(
    preview(page).getByText('Captura rápida admite una actividad a la vez.'),
  ).toBeVisible();
  await expect(preview(page).getByLabel('Tipo')).toHaveValue('EXAM');
  assertClean();
});

test('cancel creates nothing and returns focus to the text box', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page);
  await interpret(page, `parcial redes ${tomorrowName} 10am`);
  await preview(page).getByRole('button', { name: 'Cancelar' }).click();
  await expect(preview(page)).toHaveCount(0);
  await expect(textbox(page)).toBeFocused();
  await expect(textbox(page)).toHaveValue('');
  expect(await activities(page)).toHaveLength(0);
  assertClean();
});

test('"Volver a editar texto" keeps the text and focuses it', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page);
  await interpret(page, `parcial redes ${tomorrowName} 10am`);
  await preview(page).getByRole('button', { name: 'Volver a editar texto' }).click();
  await expect(preview(page)).toHaveCount(0);
  await expect(textbox(page)).toBeFocused();
  await expect(textbox(page)).toHaveValue(`parcial redes ${tomorrowName} 10am`);
  assertClean();
});

test('the preview is editable: what is created is what the student corrected', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page, ['Redes', 'Bases de Datos']);
  await interpret(page, `parcial redes ${tomorrowName} 10am`);
  const bases = (await subjects(page)).find((s) => s.name === 'Bases de Datos')!;
  const inTwoDays = bogotaToday(2);

  await preview(page).getByLabel('Título').fill('Quiz de repaso');
  await preview(page).getByLabel('Asignatura').selectOption({ label: 'Bases de Datos' });
  await preview(page).getByLabel('Tipo').selectOption({ label: 'Quiz' });
  await preview(page).getByLabel('Fecha').fill(inTwoDays);
  await preview(page).getByLabel('Hora (opcional)').fill('15:30');
  await create(page).click();
  await expect(capture(page).getByRole('status')).toContainText(
    'Actividad creada: Quiz de repaso.',
  );

  const [created] = await activities(page);
  expect(created).toMatchObject({
    title: 'Quiz de repaso',
    type: 'QUIZ',
    subjectId: bases.id,
    hasTime: true,
  });
  // 15:30 on the chosen day in Bogotá (UTC-5) is 20:30 UTC.
  expect(created!.dueAt).toBe(`${inTwoDays}T20:30:00.000Z`);
  assertClean();
});

test('empty and too long input are explained before calling anything', async ({ page }) => {
  const assertClean = watch(page);
  await newUser(page);
  await page.goto('/dashboard');
  let calls = 0;
  page.on('request', (r) => {
    if (r.url().includes('/api/quick-capture/parse')) calls++;
  });

  await capture(page).getByRole('button', { name: 'Interpretar' }).click();
  await expect(capture(page).getByRole('alert')).toHaveText(
    'Escribe una actividad para continuar.',
  );
  await expect(textbox(page)).toHaveAttribute('aria-invalid', 'true');
  await textbox(page).fill('x'.repeat(301));
  await capture(page).getByRole('button', { name: 'Interpretar' }).click();
  await expect(capture(page).getByRole('alert')).toHaveText(
    'Este texto parece demasiado largo para Captura rápida.',
  );
  expect(calls).toBe(0);
  expect(await activities(page)).toHaveLength(0);
  assertClean();
});

test('if interpreting fails the text is kept and the manual form is one click away', async ({
  page,
}) => {
  await newUser(page);
  await page.goto('/dashboard');
  await page.route('**/api/quick-capture/parse', (route) =>
    route.fulfill({
      status: 500,
      contentType: 'application/json',
      body: JSON.stringify({ error: { code: 'INTERNAL_ERROR', message: 'boom' } }),
    }),
  );
  await textbox(page).fill(`parcial redes ${tomorrowName} 10am`);
  await capture(page).getByRole('button', { name: 'Interpretar' }).click();
  await expect(capture(page).getByRole('alert')).toContainText(
    'No pudimos interpretar el texto. Puedes intentarlo de nuevo o crear la actividad manualmente.',
  );
  await expect(textbox(page)).toHaveValue(`parcial redes ${tomorrowName} 10am`);
  await capture(page).getByRole('link', { name: 'Crear manualmente' }).click();
  await expect(page).toHaveURL(/\/activities/);
  await expect(page.getByRole('dialog', { name: 'Agregar actividad' })).toBeVisible();
  // (No console check here: a mocked 500 is logged by the browser on purpose.)
});

test('accessibility: a real label, keyboard, focus and warnings tied to the preview', async ({
  page,
}) => {
  const assertClean = watch(page);
  await newUser(page);
  await page.goto('/dashboard');
  await expect(page.getByLabel('Escribe la actividad en una frase')).toBeVisible();
  // Tab order: text box -> Interpretar.
  await textbox(page).focus();
  await page.keyboard.press('Tab');
  await expect(capture(page).getByRole('button', { name: 'Interpretar' })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(capture(page).getByRole('alert')).toBeVisible();

  await textbox(page).fill('parcial mañana');
  await textbox(page).press('Enter');
  await expect(preview(page)).toBeFocused();
  const describedBy = await preview(page).getAttribute('aria-describedby');
  expect(describedBy).toBe('quick-capture-warnings');
  await expect(page.locator('#quick-capture-warnings')).toContainText(
    'No reconocí una asignatura.',
  );
  // Every control of the preview has a label.
  for (const label of ['Título', 'Asignatura', 'Tipo', 'Fecha', 'Hora (opcional)']) {
    await expect(preview(page).getByLabel(label)).toBeVisible();
  }
  // The Dashboard keeps its one h1 and h2 sections: the preview adds no headings.
  await expect(page.getByRole('heading', { level: 1 })).toHaveCount(1);
  expect(await preview(page).getByRole('heading').count()).toBe(0);
  assertClean();
});

test('layout: the input, the preview and the buttons fit the screen with a long phrase', async ({
  page,
}) => {
  const assertClean = watch(page);
  await newUser(page, [
    'Asignatura con un nombre bastante largo para comprobar el ajuste de línea',
  ]);
  const phrase = `parcial asignatura con un nombre bastante largo ${'tema'.repeat(10)} ${tomorrowName} 10am`;
  await page.goto('/dashboard');
  await textbox(page).fill(phrase);
  await expectNoHorizontalOverflow(page);
  const viewport = page.viewportSize()!;
  const box = (await textbox(page).boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(viewport.width);
  await capture(page).getByRole('button', { name: 'Interpretar' }).click();
  await expect(preview(page)).toBeVisible();
  await expectNoHorizontalOverflow(page);
  for (const label of ['Título', 'Asignatura', 'Tipo', 'Fecha', 'Hora (opcional)']) {
    const b = (await preview(page).getByLabel(label).boundingBox())!;
    expect(b.x, label).toBeGreaterThanOrEqual(0);
    expect(b.x + b.width, label).toBeLessThanOrEqual(viewport.width);
  }
  for (const name of ['Crear actividad', 'Volver a editar texto', 'Cancelar']) {
    const b = (await preview(page).getByRole('button', { name }).boundingBox())!;
    expect(b.height, name).toBeGreaterThanOrEqual(44);
    expect(b.x + b.width, name).toBeLessThanOrEqual(viewport.width);
  }
  assertClean();
});

test('"hoy" is the profile’s day, not the browser’s', async ({ browser }) => {
  // The browser believes it is in Tokyo (UTC+9); the profile is Bogotá (UTC-5).
  const context = await browser.newContext({ timezoneId: 'Asia/Tokyo', locale: 'en-US' });
  const page = await context.newPage();
  const assertClean = watch(page);
  await newUser(page);
  await interpret(page, 'lectura redes hoy');
  await expect(preview(page).getByLabel('Fecha')).toHaveValue(bogotaToday());
  await expect(preview(page).getByLabel('Tipo')).toHaveValue('READING');
  assertClean();
  await context.close();
});
